# Generated by Django 2.2 on 2020-03-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email_id', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(max_length=30)),
                ('alternate_phone', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
