# Generated by Django 2.2 on 2020-03-28 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('rate', models.FloatField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_ecart.ProductCategory')),
            ],
        ),
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('cart_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_actual_amount', models.FloatField(max_length=20)),
                ('total_discounted_amount', models.FloatField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_ecart.User')),
            ],
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('cart_item_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('qty', models.FloatField(max_length=20)),
                ('amount', models.FloatField(max_length=20)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_ecart.CartOrder')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_ecart.Product')),
            ],
        ),
    ]
